name: Build LaTeX document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          
      - name: Check pdf file
        run: |
          file cv.pdf | grep -q ' PDF '

      - name: Upload file to repository
        run: |
          git config --global user.name "ismael-mendoza"
          git config --global user.email "imendoza@umich.edu"
          git add cv.pdf
          git commit -m "upload latest CV PDF"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
